name: country_list_picker
description: Flutter plugin project to pick country code, will show code country, dial code, flag country, and name country.
version: 0.0.1
homepage: https://github.com/AmremadDev/country-list-picker.git
# publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/flags/
 