List<Map> countriesEnglish = [
  {
    "name": "Afghanistan",
    "dial_code": "+93",
    "code": "AF",
    "Length": "12",
  },
  {
    "name": "Aland Islands",
    "dial_code": "+358",
    "code": "AX",
    "Length": "12",
  },
  {
    "name": "Albania",
    "dial_code": "+355",
    "code": "AL",
    "Length": "12",
  },
  {
    "name": "Algeria",
    "dial_code": "+213",
    "code": "DZ",
    "Length": "12",
  },
  {
    "name": "AmericanSamoa",
    "dial_code": "+1684",
    "code": "AS",
    "Length": "12",
  },
  {
    "name": "Andorra",
    "dial_code": "+376",
    "code": "AD",
    "Length": "12",
  },
  {
    "name": "Angola",
    "dial_code": "+244",
    "code": "AO",
    "Length": "12",
  },
  {
    "name": "Anguilla",
    "dial_code": "+1264",
    "code": "AI",
    "Length": "12",
  },
  {
    "name": "Antarctica",
    "dial_code": "+672",
    "code": "AQ",
    "Length": "12",
  },
  {
    "name": "Antigua and Barbuda",
    "dial_code": "+1268",
    "code": "AG",
    "Length": "12",
  },
  {
    "name": "Argentina",
    "dial_code": "+54",
    "code": "AR",
    "Length": "12",
  },
  {
    "name": "Armenia",
    "dial_code": "+374",
    "code": "AM",
    "Length": "12",
  },
  {
    "name": "Aruba",
    "dial_code": "+297",
    "code": "AW",
    "Length": "12",
  },
  {
    "name": "Australia",
    "dial_code": "+61",
    "code": "AU",
    "Length": "12",
  },
  {
    "name": "Austria",
    "dial_code": "+43",
    "code": "AT",
    "Length": "12",
  },
  {
    "name": "Azerbaijan",
    "dial_code": "+994",
    "code": "AZ",
    "Length": "12",
  },
  {
    "name": "Bahamas",
    "dial_code": "+1242",
    "code": "BS",
    "Length": "12",
  },
  {
    "name": "Bahrain",
    "dial_code": "+973",
    "code": "BH",
    "Length": "12",
  },
  {
    "name": "Bangladesh",
    "dial_code": "+880",
    "code": "BD",
    "Length": "12",
  },
  {
    "name": "Barbados",
    "dial_code": "+1246",
    "code": "BB",
    "Length": "12",
  },
  {
    "name": "Belarus",
    "dial_code": "+375",
    "code": "BY",
    "Length": "12",
  },
  {
    "name": "Belgium",
    "dial_code": "+32",
    "code": "BE",
    "Length": "12",
  },
  {
    "name": "Belize",
    "dial_code": "+501",
    "code": "BZ",
    "Length": "12",
  },
  {
    "name": "Benin",
    "dial_code": "+229",
    "code": "BJ",
    "Length": "12",
  },
  {
    "name": "Bermuda",
    "dial_code": "+1441",
    "code": "BM",
    "Length": "12",
  },
  {
    "name": "Bhutan",
    "dial_code": "+975",
    "code": "BT",
    "Length": "12",
  },
  {
    "name": "Bolivia, Plurinational State of",
    "dial_code": "+591",
    "code": "BO",
    "Length": "12",
  },
  {
    "name": "Bosnia and Herzegovina",
    "dial_code": "+387",
    "code": "BA",
    "Length": "12",
  },
  {
    "name": "Botswana",
    "dial_code": "+267",
    "code": "BW",
    "Length": "12",
  },
  {
    "name": "Brazil",
    "dial_code": "+55",
    "code": "BR",
    "Length": "12",
  },
  {
    "name": "British Indian Ocean Territory",
    "dial_code": "+246",
    "code": "IO",
    "Length": "12",
  },
  {
    "name": "Brunei Darussalam",
    "dial_code": "+673",
    "code": "BN",
    "Length": "12",
  },
  {
    "name": "Bulgaria",
    "dial_code": "+359",
    "code": "BG",
    "Length": "12",
  },
  {
    "name": "Burkina Faso",
    "dial_code": "+226",
    "code": "BF",
    "Length": "12",
  },
  {
    "name": "Burundi",
    "dial_code": "+257",
    "code": "BI",
    "Length": "12",
  },
  {
    "name": "Cambodia",
    "dial_code": "+855",
    "code": "KH",
    "Length": "12",
  },
  {
    "name": "Cameroon",
    "dial_code": "+237",
    "code": "CM",
    "Length": "12",
  },
  {
    "name": "Canada",
    "dial_code": "+1",
    "code": "CA",
    "Length": "12",
  },
  {
    "name": "Cape Verde",
    "dial_code": "+238",
    "code": "CV",
    "Length": "12",
  },
  {
    "name": "Cayman Islands",
    "dial_code": "+ 345",
    "code": "KY",
    "Length": "12",
  },
  {
    "name": "Central African Republic",
    "dial_code": "+236",
    "code": "CF",
    "Length": "12",
  },
  {
    "name": "Chad",
    "dial_code": "+235",
    "code": "TD",
    "Length": "12",
  },
  {
    "name": "Chile",
    "dial_code": "+56",
    "code": "CL",
    "Length": "12",
  },
  {
    "name": "China",
    "dial_code": "+86",
    "code": "CN",
    "Length": "12",
  },
  {
    "name": "Christmas Island",
    "dial_code": "+61",
    "code": "CX",
    "Length": "12",
  },
  {
    "name": "Cocos (Keeling) Islands",
    "dial_code": "+61",
    "code": "CC",
    "Length": "12",
  },
  {
    "name": "Colombia",
    "dial_code": "+57",
    "code": "CO",
    "Length": "12",
  },
  {
    "name": "Comoros",
    "dial_code": "+269",
    "code": "KM",
    "Length": "12",
  },
  {
    "name": "Congo",
    "dial_code": "+242",
    "code": "CG",
    "Length": "12",
  },
  {
    "name": "Congo, The Democratic Republic\n of the Congo",
    "dial_code": "+243",
    "code": "CD",
    "Length": "12",
  },
  {
    "name": "Cook Islands",
    "dial_code": "+682",
    "code": "CK",
    "Length": "12",
  },
  {
    "name": "Costa Rica",
    "dial_code": "+506",
    "code": "CR",
    "Length": "12",
  },
  {
    "name": "Cote d'Ivoire",
    "dial_code": "+225",
    "code": "CI",
    "Length": "12",
  },
  {
    "name": "Croatia",
    "dial_code": "+385",
    "code": "HR",
    "Length": "12",
  },
  {
    "name": "Cuba",
    "dial_code": "+53",
    "code": "CU",
    "Length": "12",
  },
  {
    "name": "Cyprus",
    "dial_code": "+357",
    "code": "CY",
    "Length": "12",
  },
  {
    "name": "Czech Republic",
    "dial_code": "+420",
    "code": "CZ",
    "Length": "12",
  },
  {
    "name": "Denmark",
    "dial_code": "+45",
    "code": "DK",
    "Length": "12",
  },
  {
    "name": "Djibouti",
    "dial_code": "+253",
    "code": "DJ",
    "Length": "12",
  },
  {
    "name": "Dominica",
    "dial_code": "+1767",
    "code": "DM",
    "Length": "12",
  },
  {
    "name": "Dominican Republic",
    "dial_code": "+1849",
    "code": "DO",
    "Length": "12",
  },
  {
    "name": "Ecuador",
    "dial_code": "+593",
    "code": "EC",
    "Length": "12",
  },
  {
    "name": "Egypt",
    "dial_code": "+20",
    "code": "EG",
    "Length": "12",
  },
  {
    "name": "El Salvador",
    "dial_code": "+503",
    "code": "SV",
    "Length": "12",
  },
  {
    "name": "Equatorial Guinea",
    "dial_code": "+240",
    "code": "GQ",
    "Length": "12",
  },
  {
    "name": "Eritrea",
    "dial_code": "+291",
    "code": "ER",
    "Length": "12",
  },
  {
    "name": "Estonia",
    "dial_code": "+372",
    "code": "EE",
    "Length": "12",
  },
  {
    "name": "Ethiopia",
    "dial_code": "+251",
    "code": "ET",
    "Length": "12",
  },
  {
    "name": "Falkland Islands (Malvinas)",
    "dial_code": "+500",
    "code": "FK",
    "Length": "12",
  },
  {
    "name": "Faroe Islands",
    "dial_code": "+298",
    "code": "FO",
    "Length": "12",
  },
  {
    "name": "Fiji",
    "dial_code": "+679",
    "code": "FJ",
    "Length": "12",
  },
  {
    "name": "Finland",
    "dial_code": "+358",
    "code": "FI",
    "Length": "12",
  },
  {
    "name": "France",
    "dial_code": "+33",
    "code": "FR",
    "Length": "12",
  },
  {
    "name": "French Guiana",
    "dial_code": "+594",
    "code": "GF",
    "Length": "12",
  },
  {
    "name": "French Polynesia",
    "dial_code": "+689",
    "code": "PF",
    "Length": "12",
  },
  {
    "name": "Gabon",
    "dial_code": "+241",
    "code": "GA",
    "Length": "12",
  },
  {
    "name": "Gambia",
    "dial_code": "+220",
    "code": "GM",
    "Length": "12",
  },
  {
    "name": "Georgia",
    "dial_code": "+995",
    "code": "GE",
    "Length": "12",
  },
  {
    "name": "Germany",
    "dial_code": "+49",
    "code": "DE",
    "Length": "12",
  },
  {
    "name": "Ghana",
    "dial_code": "+233",
    "code": "GH",
    "Length": "12",
  },
  {
    "name": "Gibraltar",
    "dial_code": "+350",
    "code": "GI",
    "Length": "12",
  },
  {
    "name": "Greece",
    "dial_code": "+30",
    "code": "GR",
    "Length": "12",
  },
  {
    "name": "Greenland",
    "dial_code": "+299",
    "code": "GL",
    "Length": "12",
  },
  {
    "name": "Grenada",
    "dial_code": "+1473",
    "code": "GD",
    "Length": "12",
  },
  {
    "name": "Guadeloupe",
    "dial_code": "+590",
    "code": "GP",
    "Length": "12",
  },
  {
    "name": "Guam",
    "dial_code": "+1671",
    "code": "GU",
    "Length": "12",
  },
  {
    "name": "Guatemala",
    "dial_code": "+502",
    "code": "GT",
    "Length": "12",
  },
  {
    "name": "Guernsey",
    "dial_code": "+44",
    "code": "GG",
    "Length": "12",
  },
  {
    "name": "Guinea",
    "dial_code": "+224",
    "code": "GN",
    "Length": "12",
  },
  {
    "name": "Guinea-Bissau",
    "dial_code": "+245",
    "code": "GW",
    "Length": "12",
  },
  {
    "name": "Guyana",
    "dial_code": "+595",
    "code": "GY",
    "Length": "12",
  },
  {
    "name": "Haiti",
    "dial_code": "+509",
    "code": "HT",
    "Length": "12",
  },
  {
    "name": "Holy See (Vatican City State)",
    "dial_code": "+379",
    "code": "VA",
    "Length": "12",
  },
  {
    "name": "Honduras",
    "dial_code": "+504",
    "code": "HN",
    "Length": "12",
  },
  {
    "name": "Hong Kong",
    "dial_code": "+852",
    "code": "HK",
    "Length": "12",
  },
  {
    "name": "Hungary",
    "dial_code": "+36",
    "code": "HU",
    "Length": "12",
  },
  {
    "name": "Iceland",
    "dial_code": "+354",
    "code": "IS",
    "Length": "12",
  },
  {
    "name": "India",
    "dial_code": "+91",
    "code": "IN",
    "Length": "12",
  },
  {
    "name": "Indonesia",
    "dial_code": "+62",
    "code": "ID",
    "Length": "12",
  },
  {
    "name": "Iran, Islamic Republic of Persian Gulf",
    "dial_code": "+98",
    "code": "IR",
    "Length": "12",
  },
  {
    "name": "Iraq",
    "dial_code": "+964",
    "code": "IQ",
    "Length": "12",
  },
  {
    "name": "Ireland",
    "dial_code": "+353",
    "code": "IE",
    "Length": "12",
  },
  {
    "name": "Isle of Man",
    "dial_code": "+44",
    "code": "IM",
    "Length": "12",
  },
  {
    "name": "Palestine",
    "dial_code": "+972",
    "code": "IL",
    "Length": "12",
  },
  {
    "name": "Italy",
    "dial_code": "+39",
    "code": "IT",
    "Length": "12",
  },
  {
    "name": "Jamaica",
    "dial_code": "+1876",
    "code": "JM",
    "Length": "12",
  },
  {
    "name": "Japan",
    "dial_code": "+81",
    "code": "JP",
    "Length": "12",
  },
  {
    "name": "Jersey",
    "dial_code": "+44",
    "code": "JE",
    "Length": "12",
  },
  {
    "name": "Jordan",
    "dial_code": "+962",
    "code": "JO",
    "Length": "12",
  },
  {
    "name": "Kazakhstan",
    "dial_code": "+77",
    "code": "KZ",
    "Length": "12",
  },
  {
    "name": "Kenya",
    "dial_code": "+254",
    "code": "KE",
    "Length": "12",
  },
  {
    "name": "Kiribati",
    "dial_code": "+686",
    "code": "KI",
    "Length": "12",
  },
  {
    "name": "Korea, Democratic People's\nRepublic of Korea",
    "dial_code": "+850",
    "code": "KP",
    "Length": "12",
  },
  {
    "name": "Korea, Republic of South Korea",
    "dial_code": "+82",
    "code": "KR",
    "Length": "12",
  },
  {
    "name": "Kuwait",
    "dial_code": "+965",
    "code": "KW",
    "Length": "12",
  },
  {
    "name": "Kyrgyzstan",
    "dial_code": "+996",
    "code": "KG",
    "Length": "12",
  },
  {
    "name": "Laos",
    "dial_code": "+856",
    "code": "LA",
    "Length": "12",
  },
  {
    "name": "Latvia",
    "dial_code": "+371",
    "code": "LV",
    "Length": "12",
  },
  {
    "name": "Lebanon",
    "dial_code": "+961",
    "code": "LB",
    "Length": "12",
  },
  {
    "name": "Lesotho",
    "dial_code": "+266",
    "code": "LS",
    "Length": "12",
  },
  {
    "name": "Liberia",
    "dial_code": "+231",
    "code": "LR",
    "Length": "12",
  },
  {
    "name": "Libyan Arab Jamahiriya",
    "dial_code": "+218",
    "code": "LY",
    "Length": "12",
  },
  {
    "name": "Liechtenstein",
    "dial_code": "+423",
    "code": "LI",
    "Length": "12",
  },
  {
    "name": "Lithuania",
    "dial_code": "+370",
    "code": "LT",
    "Length": "12",
  },
  {
    "name": "Luxembourg",
    "dial_code": "+352",
    "code": "LU",
    "Length": "12",
  },
  {
    "name": "Macao",
    "dial_code": "+853",
    "code": "MO",
    "Length": "12",
  },
  {
    "name": "Macedonia",
    "dial_code": "+389",
    "code": "MK",
    "Length": "12",
  },
  {
    "name": "Madagascar",
    "dial_code": "+261",
    "code": "MG",
    "Length": "12",
  },
  {
    "name": "Malawi",
    "dial_code": "+265",
    "code": "MW",
    "Length": "12",
  },
  {
    "name": "Malaysia",
    "dial_code": "+60",
    "code": "MY",
    "Length": "12",
  },
  {
    "name": "Maldives",
    "dial_code": "+960",
    "code": "MV",
    "Length": "12",
  },
  {
    "name": "Mali",
    "dial_code": "+223",
    "code": "ML",
    "Length": "12",
  },
  {
    "name": "Malta",
    "dial_code": "+356",
    "code": "MT",
    "Length": "12",
  },
  {
    "name": "Marshall Islands",
    "dial_code": "+692",
    "code": "MH",
    "Length": "12",
  },
  {
    "name": "Martinique",
    "dial_code": "+596",
    "code": "MQ",
    "Length": "12",
  },
  {
    "name": "Mauritania",
    "dial_code": "+222",
    "code": "MR",
    "Length": "12",
  },
  {
    "name": "Mauritius",
    "dial_code": "+230",
    "code": "MU",
    "Length": "12",
  },
  {
    "name": "Mayotte",
    "dial_code": "+262",
    "code": "YT",
    "Length": "12",
  },
  {
    "name": "Mexico",
    "dial_code": "+52",
    "code": "MX",
    "Length": "12",
  },
  {
    "name": "Micronesia, Federated States of Micronesia",
    "dial_code": "+691",
    "code": "FM",
    "Length": "12",
  },
  {
    "name": "Moldova",
    "dial_code": "+373",
    "code": "MD",
    "Length": "12",
  },
  {
    "name": "Monaco",
    "dial_code": "+377",
    "code": "MC",
    "Length": "12",
  },
  {
    "name": "Mongolia",
    "dial_code": "+976",
    "code": "MN",
    "Length": "12",
  },
  {
    "name": "Montenegro",
    "dial_code": "+382",
    "code": "ME",
    "Length": "12",
  },
  {
    "name": "Montserrat",
    "dial_code": "+1664",
    "code": "MS",
    "Length": "12",
  },
  {
    "name": "Morocco",
    "dial_code": "+212",
    "code": "MA",
    "Length": "12",
  },
  {
    "name": "Mozambique",
    "dial_code": "+258",
    "code": "MZ",
    "Length": "12",
  },
  {
    "name": "Myanmar",
    "dial_code": "+95",
    "code": "MM",
    "Length": "12",
  },
  {
    "name": "Namibia",
    "dial_code": "+264",
    "code": "NA",
    "Length": "12",
  },
  {
    "name": "Nauru",
    "dial_code": "+674",
    "code": "NR",
    "Length": "12",
  },
  {
    "name": "Nepal",
    "dial_code": "+977",
    "code": "NP",
    "Length": "12",
  },
  {
    "name": "Netherlands",
    "dial_code": "+31",
    "code": "NL",
    "Length": "12",
  },
  {
    "name": "Netherlands Antilles",
    "dial_code": "+599",
    "code": "AN",
    "Length": "12",
  },
  {
    "name": "New Caledonia",
    "dial_code": "+687",
    "code": "NC",
    "Length": "12",
  },
  {
    "name": "New Zealand",
    "dial_code": "+64",
    "code": "NZ",
    "Length": "12",
  },
  {
    "name": "Nicaragua",
    "dial_code": "+505",
    "code": "NI",
    "Length": "12",
  },
  {
    "name": "Niger",
    "dial_code": "+227",
    "code": "NE",
    "Length": "12",
  },
  {
    "name": "Nigeria",
    "dial_code": "+234",
    "code": "NG",
    "Length": "12",
  },
  {
    "name": "Niue",
    "dial_code": "+683",
    "code": "NU",
    "Length": "12",
  },
  {
    "name": "Norfolk Island",
    "dial_code": "+672",
    "code": "NF",
    "Length": "12",
  },
  {
    "name": "Northern Mariana Islands",
    "dial_code": "+1670",
    "code": "MP",
    "Length": "12",
  },
  {
    "name": "Norway",
    "dial_code": "+47",
    "code": "NO",
    "Length": "12",
  },
  {
    "name": "Oman",
    "dial_code": "+968",
    "code": "OM",
    "Length": "12",
  },
  {
    "name": "Pakistan",
    "dial_code": "+92",
    "code": "PK",
    "Length": "12",
  },
  {
    "name": "Palau",
    "dial_code": "+680",
    "code": "PW",
    "Length": "12",
  },
  {
    "name": "Palestinian Territory, Occupied",
    "dial_code": "+970",
    "code": "PS",
    "Length": "12",
  },
  {
    "name": "Panama",
    "dial_code": "+507",
    "code": "PA",
    "Length": "12",
  },
  {
    "name": "Papua New Guinea",
    "dial_code": "+675",
    "code": "PG",
    "Length": "12",
  },
  {
    "name": "Paraguay",
    "dial_code": "+595",
    "code": "PY",
    "Length": "12",
  },
  {
    "name": "Peru",
    "dial_code": "+51",
    "code": "PE",
    "Length": "12",
  },
  {
    "name": "Philippines",
    "dial_code": "+63",
    "code": "PH",
    "Length": "12",
  },
  {
    "name": "Pitcairn",
    "dial_code": "+872",
    "code": "PN",
    "Length": "12",
  },
  {
    "name": "Poland",
    "dial_code": "+48",
    "code": "PL",
    "Length": "12",
  },
  {
    "name": "Portugal",
    "dial_code": "+351",
    "code": "PT",
    "Length": "12",
  },
  {
    "name": "Puerto Rico",
    "dial_code": "+1939",
    "code": "PR",
    "Length": "12",
  },
  {
    "name": "Qatar",
    "dial_code": "+974",
    "code": "QA",
    "Length": "12",
  },
  {
    "name": "Romania",
    "dial_code": "+40",
    "code": "RO",
    "Length": "12",
  },
  {
    "name": "Russia",
    "dial_code": "+7",
    "code": "RU",
    "Length": "12",
  },
  {
    "name": "Rwanda",
    "dial_code": "+250",
    "code": "RW",
    "Length": "12",
  },
  {
    "name": "Reunion",
    "dial_code": "+262",
    "code": "RE",
    "Length": "12",
  },
  {
    "name": "Saint Barthelemy",
    "dial_code": "+590",
    "code": "BL",
    "Length": "12",
  },
  {
    "name": "Saint Helena, Ascension and Tristan Da Cunha",
    "dial_code": "+290",
    "code": "SH",
    "Length": "12",
  },
  {
    "name": "Saint Kitts and Nevis",
    "dial_code": "+1869",
    "code": "KN",
    "Length": "12",
  },
  {
    "name": "Saint Lucia",
    "dial_code": "+1758",
    "code": "LC",
    "Length": "12",
  },
  {
    "name": "Saint Martin",
    "dial_code": "+590",
    "code": "MF",
    "Length": "12",
  },
  {
    "name": "Saint Pierre and Miquelon",
    "dial_code": "+508",
    "code": "PM",
    "Length": "12",
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "dial_code": "+1784",
    "code": "VC",
    "Length": "12",
  },
  {
    "name": "Samoa",
    "dial_code": "+685",
    "code": "WS",
    "Length": "12",
  },
  {
    "name": "San Marino",
    "dial_code": "+378",
    "code": "SM",
    "Length": "12",
  },
  {
    "name": "Sao Tome and Principe",
    "dial_code": "+239",
    "code": "ST",
    "Length": "12",
  },
  {
    "name": "Saudi Arabia",
    "dial_code": "+966",
    "code": "SA",
    "Length": "12",
  },
  {
    "name": "Senegal",
    "dial_code": "+221",
    "code": "SN",
    "Length": "12",
  },
  {
    "name": "Serbia",
    "dial_code": "+381",
    "code": "RS",
    "Length": "12",
  },
  {
    "name": "Seychelles",
    "dial_code": "+248",
    "code": "SC",
    "Length": "12",
  },
  {
    "name": "Sierra Leone",
    "dial_code": "+232",
    "code": "SL",
    "Length": "12",
  },
  {
    "name": "Singapore",
    "dial_code": "+65",
    "code": "SG",
    "Length": "12",
  },
  {
    "name": "Slovakia",
    "dial_code": "+421",
    "code": "SK",
    "Length": "12",
  },
  {
    "name": "Slovenia",
    "dial_code": "+386",
    "code": "SI",
    "Length": "12",
  },
  {
    "name": "Solomon Islands",
    "dial_code": "+677",
    "code": "SB",
    "Length": "12",
  },
  {
    "name": "Somalia",
    "dial_code": "+252",
    "code": "SO",
    "Length": "12",
  },
  {
    "name": "South Africa",
    "dial_code": "+27",
    "code": "ZA",
    "Length": "12",
  },
  {
    "name": "South Sudan",
    "dial_code": "+211",
    "code": "SS",
    "Length": "12",
  },
  {
    "name": "South Georgia and the South Sandwich Islands",
    "dial_code": "+500",
    "code": "GS",
    "Length": "12",
  },
  {
    "name": "Spain",
    "dial_code": "+34",
    "code": "ES",
    "Length": "12",
  },
  {
    "name": "Sri Lanka",
    "dial_code": "+94",
    "code": "LK",
    "Length": "12",
  },
  {
    "name": "Sudan",
    "dial_code": "+249",
    "code": "SD",
    "Length": "12",
  },
  {
    "name": "Suriname",
    "dial_code": "+597",
    "code": "SR",
    "Length": "12",
  },
  {
    "name": "Svalbard and Jan Mayen",
    "dial_code": "+47",
    "code": "SJ",
    "Length": "12",
  },
  {
    "name": "Swaziland",
    "dial_code": "+268",
    "code": "SZ",
    "Length": "12",
  },
  {
    "name": "Sweden",
    "dial_code": "+46",
    "code": "SE",
    "Length": "12",
  },
  {
    "name": "Switzerland",
    "dial_code": "+41",
    "code": "CH",
    "Length": "12",
  },
  {
    "name": "Syrian Arab Republic",
    "dial_code": "+963",
    "code": "SY",
    "Length": "12",
  },
  {
    "name": "Taiwan",
    "dial_code": "+886",
    "code": "TW",
    "Length": "12",
  },
  {
    "name": "Tajikistan",
    "dial_code": "+992",
    "code": "TJ",
    "Length": "12",
  },
  {
    "name": "Tanzania, United Republic of Tanzania",
    "dial_code": "+255",
    "code": "TZ",
    "Length": "12",
  },
  {
    "name": "Thailand",
    "dial_code": "+66",
    "code": "TH",
    "Length": "12",
  },
  {
    "name": "Timor-Leste",
    "dial_code": "+670",
    "code": "TL",
    "Length": "12",
  },
  {
    "name": "Togo",
    "dial_code": "+228",
    "code": "TG",
    "Length": "12",
  },
  {
    "name": "Tokelau",
    "dial_code": "+690",
    "code": "TK",
    "Length": "12",
  },
  {
    "name": "Tonga",
    "dial_code": "+676",
    "code": "TO",
    "Length": "12",
  },
  {
    "name": "Trinidad and Tobago",
    "dial_code": "+1868",
    "code": "TT",
    "Length": "12",
  },
  {
    "name": "Tunisia",
    "dial_code": "+216",
    "code": "TN",
    "Length": "12",
  },
  {
    "name": "Turkey",
    "dial_code": "+90",
    "code": "TR",
    "Length": "12",
  },
  {
    "name": "Turkmenistan",
    "dial_code": "+993",
    "code": "TM",
    "Length": "12",
  },
  {
    "name": "Turks and Caicos Islands",
    "dial_code": "+1649",
    "code": "TC",
    "Length": "12",
  },
  {
    "name": "Tuvalu",
    "dial_code": "+688",
    "code": "TV",
    "Length": "12",
  },
  {
    "name": "Uganda",
    "dial_code": "+256",
    "code": "UG",
    "Length": "12",
  },
  {
    "name": "Ukraine",
    "dial_code": "+380",
    "code": "UA",
    "Length": "12",
  },
  {
    "name": "United Arab Emirates",
    "dial_code": "+971",
    "code": "AE",
    "Length": "12",
  },
  {
    "name": "United Kingdom",
    "dial_code": "+44",
    "code": "GB",
    "Length": "12",
  },
  {
    "name": "United States",
    "dial_code": "+1",
    "code": "US",
    "Length": "12",
  },
  {
    "name": "Uruguay",
    "dial_code": "+598",
    "code": "UY",
    "Length": "12",
  },
  {
    "name": "Uzbekistan",
    "dial_code": "+998",
    "code": "UZ",
    "Length": "12",
  },
  {
    "name": "Vanuatu",
    "dial_code": "+678",
    "code": "VU",
    "Length": "12",
  },
  {
    "name": "Venezuela, Bolivarian Republic of Venezuela",
    "dial_code": "+58",
    "code": "VE",
    "Length": "12",
  },
  {
    "name": "Vietnam",
    "dial_code": "+84",
    "code": "VN",
    "Length": "12",
  },
  {
    "name": "Virgin Islands, British",
    "dial_code": "+1284",
    "code": "VG",
    "Length": "12",
  },
  {
    "name": "Virgin Islands, U.S.",
    "dial_code": "+1340",
    "code": "VI",
    "Length": "12",
  },
  {
    "name": "Wallis and Futuna",
    "dial_code": "+681",
    "code": "WF",
    "Length": "12",
  },
  {
    "name": "Yemen",
    "dial_code": "+967",
    "code": "YE",
    "Length": "12",
  },
  {
    "name": "Zambia",
    "dial_code": "+260",
    "code": "ZM",
    "Length": "12",
  },
  {
    "name": "Zimbabwe",
    "dial_code": "+263",
    "code": "ZW",
    "Length": "12",
  }
];
